services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    privileged: true
    stdin_open: true
    tty: true
    entrypoint: /app/build/entrypoint.sh
    volumes:
      - /dev:/dev
      - .:/app
      - /app/hardware_communication  # Preserves hw_comms binary
      - /app/build