import board
from eeprom import EepromDevice

# PASTE YOUR ONE-LINE BASE64 KEY HERE (Generated by generate_keys.py)
KEY_BODY = "MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAz/pguxdVR7OMOCJSgBvLySnJv9E0JoLiQkoj1XL/1eUdiTbdq/1cmPIO5mzTVtPDvzmcXVvhsFfMbsxqyaTRqwIDAQABAkAhCepR7kv63vf4duNaPJAr/bpyAV7ie0pMM5DruKARr1GX0lJF8zo4J5/9MS0geZDZZYByJjIZFSvjESFDdWzpAiEA8N9GSGQ4EJ84mkwqvg7cNv0zwhkB0vIqYsRccIRTy28CIQDdCjvfm3w2hi7K3dmrNgyEQDtDvUqJHgt0oHQmUglvhQIgJBiBcsW59Ru3IsA5Q4P8kiz9fZ+7uz3ZBjYA2EesOvcCIQCoAp1b631QnFF41YQbxStiYsgpRvoemv2uGj/u2LBfWQIgG17Y9+yF+UJll5/63mj9zyB17R0aIm3K5XcdmCqhqIs=" 

# Initialize the EEPROM device using the I2C pins on the Raspberry Pi Pico
eeprom = EepromDevice(scl_pin=board.GP1, sda_pin=board.GP0)

print(f"Writing {len(KEY_BODY)} bytes to EEPROM...")

# The AT24CS04 EEPROM has exactly 512 bytes of total storage. 
# We reserve the first 2 bytes for the length metadata, leaving 510 bytes max for the key.
if len(KEY_BODY) > 510:
    print("Error: Key is still too big!")
else:
    # Get the length of the string to store in the first 2 bytes (addresses 0 and 1)
    length = len(KEY_BODY)
    
    # Store the length as a 16-bit integer across two 8-bit registers:
    # Bitwise shift right by 8 to get the most significant byte (MSB)
    eeprom.write_byte(0, (length >> 8) & 0xFF)
    # Bitwise AND with 0xFF to get the least significant byte (LSB)
    eeprom.write_byte(1, length & 0xFF)

    # Write the actual Base64 string characters starting at memory address 2
    for i in range(length):
        # Convert the character to its ASCII integer value using ord() and write it
        eeprom.write_byte(i + 2, ord(KEY_BODY[i]))
        
    print("Done.")