import board
from eeprom import EepromDevice

# PASTE YOUR ONE-LINE BASE64 KEY HERE (Generated by generate_keys.py)
KEY_BODY = "PASTE YOUR SECRET KEY HERE"

if KEY_BODY == "PASTE YOUR SECRET KEY HERE":
    print("Paste your unique, private key before running this script")
    exit()

# Initialize the EEPROM device using the I2C pins on the Raspberry Pi Pico
eeprom = EepromDevice(scl_pin=board.GP5, sda_pin=board.GP4)

print(f"Writing {len(KEY_BODY)} bytes to EEPROM...")

# The AT24CS04 EEPROM has exactly 512 bytes of total storage. 
# We reserve the first 2 bytes for the length metadata, leaving 510 bytes max for the key.
if len(KEY_BODY) > 510:
    print("Error: Key is still too big!")
else:
    # Get the length of the string to store in the first 2 bytes (addresses 0 and 1)
    length = len(KEY_BODY)
    
    # Store the length as a 16-bit integer across two 8-bit registers:
    # Bitwise shift right by 8 to get the most significant byte (MSB)
    eeprom.write_byte(0, (length >> 8) & 0xFF)
    # Bitwise AND with 0xFF to get the least significant byte (LSB)
    eeprom.write_byte(1, length & 0xFF)

    # Write the actual Base64 string characters starting at memory address 2
    for i in range(length):
        # Convert the character to its ASCII integer value using ord() and write it
        eeprom.write_byte(i + 2, ord(KEY_BODY[i]))
        
    print("Done.")